### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by SandipBR** [maalik0786/FastYolo#12]
With VS Community 2019 16.11.8 and .NET 5.0 (also with .NetFrameWork 4.7.2) after putting everything in place I am getting this exception. If it is Any CPU, x86 or x64 does not make a difference.  

System.BadImageFormatException
  HResult=0x8007000B
  Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
  Source=FastYolo
  StackTrace:
   at FastYolo.YoloWrapper.GetDeviceCount()
   at FastYolo.YoloWrapper.Initialize(String configurationFilename, String weightsFilename, Int32 gpu)
   at yolo_old.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\sandi\Desktop\yolo_old\yolo_old\Form1.cs:line 24
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Another computer with VS Community 2019 16.10.1 everything works fine even in Any CPU mode.

What can be the problem ? How to fix it? 

Please help

**Comment by SandipBR** [comment]
Any way to resolve this ?

**Comment by maalik0786** [comment]
Fixed in latest release 11.6.2
